# Generated by Django 5.2.4 on 2025-07-12 07:28

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='availability',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
